

CeruleanCave_SecretChamber_B3F_Text_MillyIntro::
	.string "Hi! I'm sure you're wondering how it's\n"
	.string "raining this deep undergound.\p"
	.string "To that I say, ''Don't think about it\n"
	.string "so hard''!\p"
	.string "I just LOVE the rain!\p"
	.string "''Monsoon Milly,'' that's what\n"
	.string "everyone calls me.\p"
	.string "Well, my friends sometimes call me\n"
	.string "''Moist Milly'' instead.\p"
	.string "I love standing in the rain and\n"
	.string "letting it soak into my hair and\l"
	.string "clothing.\p"
	.string "And when it's time to come inside,\n"
	.string "I'll hop right in the shower, too.\p"
	.string "I just love being wet!\p"
	.string "Think you can beat a rain team in a\n"
	.string "perpetual downpour?\p"
	.string "I'll show you just how slippery we\n"
	.string "can be!$"

@ After you've defeated MILLY, but not yet AMY:
CeruleanCave_SecretChamber_B3F_Text_MillyRematchIntro::
	.string "Welcome back. Are you ready to\n"
	.string "try again? Let's go!$"

@ After you've defeated AMY:
CeruleanCave_SecretChamber_B3F_Text_MillyRematch2Intro::
	.string "Welcome back. Let's go!$"

CeruleanCave_SecretChamber_B3F_Text_MillyDefeat::
	.string "Nicely done.$"

CeruleanCave_SecretChamber_B3F_Text_MillyPostBattle::
	.string "But first, please allow me to heal\n"
	.string "your living teammates.$"

CeruleanCave_SecretChamber_B3F_Text_MillyPostHeal::
	.string "Since you beat me, I'll teach it\n"
	.string "to one of your POKéMON if you like.\p"
	.string "This isn't a one-time offer, either,\n"
	.string "but you'll have to beat me again\l"
	.string "before I'll teach it again.$"

CeruleanCave_SecretChamber_B3F_Text_MillyTeach::
	.string "Shall I teach Mail Script to one of\n"
	.string "your POKéMON?$"

CeruleanCave_SecretChamber_B3F_Text_MillyWhichMon::
	.string "Who should learn Mail Script?$"

CeruleanCave_SecretChamber_B3F_Text_MillyPostTeach::
	.string "Now, a word of caution before you\n"
	.string "move on: If you leave this cave,\l"
	.string "you will have to start all over!\p"
	.string "I'm going to go on ahead and then\n"
	.string "I'll see you in the final chamber\l"
	.string "should you make it that far.\p"
	.string "Good luck, and stay cute!$"


