

CeruleanCave_SecretChamber_B3F_Text_MollyIntro::
	.string "Hi! I'm sure you're wondering how it's\n"
	.string "raining this deep undergound.\p"
	.string "To that I say, “Don't think about it\n"
	.string "so hard”!\p"
	.string "I just LOVE the rain!\p"
	.string "“Monsoon Molly,” that's what\n"
	.string "everyone calls me.\p"
	.string "Well, my friends sometimes call me\n"
	.string "“Moist Molly” instead…\p"
	.string "I love standing in the rain and\n"
	.string "letting it soak into my hair and\l"
	.string "clothing.\p"
	.string "And when it's time to come inside,\n"
	.string "I'll hop right in the shower, too.\p"
	.string "I just love being wet!\p"
	.string "Think you can beat a rain team in a\n"
	.string "perpetual downpour?\p"
	.string "I'll show you just how slippery we\n"
	.string "can be!$"

@ After you've defeated MOLLY, but not yet AMY:
CeruleanCave_SecretChamber_B3F_Text_MollyRematchIntro::
	.string "Welcome back. Are you ready to\n"
	.string "try again? Let's go!$"

@ After you've defeated AMY:
CeruleanCave_SecretChamber_B3F_Text_MollyRematch2Intro::
	.string "Welcome back. Let's go!$"

CeruleanCave_SecretChamber_B3F_Text_MollyDefeat::
	.string "I'm all wet!$"

CeruleanCave_SecretChamber_B3F_Text_MollyPostBattle::
	.string "Go on to the next floor and dry\n"
	.string "yourself off.\p"
	.string "But first, please allow me to heal\n"
	.string "your living teammates.$"

CeruleanCave_SecretChamber_B3F_Text_MollyPostHeal::
	.string "And don't forget, if you leave this\n"
	.string "cave you will have to start all over!\p"
	.string "I'm going to go on ahead and then\n"
	.string "I'll see you in the final chamber\l"
	.string "should you make it that far.\p"
	.string "You've come a long way. Good luck!$"
