SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
    .string "…Wait! Don't say a word!\p"
    .string "You wanted this!$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
    .string "{PLAYER} received TM69\n"
    .string "from the creepy old man.$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
    .string "You already know, don't you?\n"
    .string "TM69 is MEGA LICK.\p"
    .string "It's fun to use on your POKéMON,\n"
    .string "or on older, wiser elders like me!$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .string "Where do you plan to put this?\n"
    .string "You've no room.$"

