PokemonLeague_LancesRoom_Text_Intro::
    .string "Ah! I've heard about you,\n"
    .string "{PLAYER}!\p"
    .string "I lead the ELITE FOUR.\p"
    .string "You can call me LANCE the dragon\n"
    .string "TRAINER.\p"
    .string "You know that dragons are\n"
    .string "mythical POKéMON.\p"
    .string "They're hard to catch and raise,\n"
    .string "but their powers are superior.\p"
    .string "They're virtually indestructible.\n"
    .string "There's no being clever with them.\p"
    .string "Well, are you ready to lose?\p"
    .string "Your LEAGUE challenge ends with\n"
    .string "me, {PLAYER}!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LancesRoom_Text_RematchIntro::
    .string "Ah!\n"
    .string "So, you've returned, {PLAYER}!\p"
    .string "I lead the ELITE FOUR.\p"
    .string "You can call me LANCE the dragon\n"
    .string "TRAINER.\p"
    .string "You know that dragons are\n"
    .string "mythical POKéMON.\p"
    .string "They're hard to catch and raise,\n"
    .string "but their powers are superior.\p"
    .string "They're virtually indestructible.\n"
    .string "There's no being clever with them.\p"
    .string "Well, are you ready to lose?\p"
    .string "Your LEAGUE challenge ends with\n"
    .string "me, {PLAYER}!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LancesRoom_Text_Defeat::
    .string "That's it!\p"
    .string "I hate to admit it, but you are a\n"
    .string "POKéMON master!$"

PokemonLeague_LancesRoom_Text_PostBattle::
    .string "I still can't believe my dragons\n"
    .string "lost to you, {PLAYER}.\p"
    .string "You have one more challenge left.\n"
    .string "There is one more TRAINER to face!$"

PokemonLeague_LancesRoom_Text_TakeTM_INFINIBLAST::
    .string "Before you go, I want you to have\n"
    .string "this.$"

PokemonLeague_LancesRoom_Text_Received_TM_INFINIBLAST::
    .string "{PLAYER} received TM59\n"
    .string "from LANCE.$"

PokemonLeague_LancesRoom_Text_ExplainTM_INFINIBLAST::
    .string "TM59 is Infiniblast, a devastating\n"
    .string "move that strikes with your highest\p"
    .string "attacking stat, but requires you to\n"
    .string "miss a turn to recharge after use.$"

