

CeruleanCave_SecretChamber_B4F_Text_NatalieIntro::
	.string "Hey.\p"
	.string "I'm Naughty Natalie… …No, don't get\n"
	.string "any ideas - I'm called that because\l"
	.string "I like to play tricks on people.\p"
	.string "You think you're clever enough to\n"
	.string "not get tricked by a little girl?\p"
	.string "Well, let's see about that!$"

@ After you've defeated NATALIE, but not yet AMY:
CeruleanCave_SecretChamber_B4F_Text_NatalieRematchIntro::
	.string "Welcome back. Are you ready to\n"
	.string "try again? Let's go!$"

@ After you've defeated AMY:
CeruleanCave_SecretChamber_B4F_Text_NatalieRematch2Intro::
	.string "Welcome back. Let's go!$"

CeruleanCave_SecretChamber_B4F_Text_NatalieDefeat::
	.string "You got me!$"

CeruleanCave_SecretChamber_B4F_Text_NataliePostBattle::
	.string "A powerful move called Mail Script\n"
	.string "allowed Courier to use several\l"
	.string "moves all at once.\p"
	.string "The moves Mail Script uses are\n"
	.string "determined by the words used in the\l"
	.string "held Mail.\p"
	.string "Since you beat me, I'll teach it\n"
	.string "to one of your POKéMON if you like.\p"
	.string "This isn't a one-time offer, either,\n"
	.string "but you'll have to beat me again\l"
	.string "before I'll teach it again.$"

CeruleanCave_SecretChamber_B4F_Text_NatalieTeach::
	.string "Shall I teach Mail Script to one of\n"
	.string "your POKéMON?$"

CeruleanCave_SecretChamber_B4F_Text_NatalieWhichMon::
	.string "Who should learn Mail Script?$"

CeruleanCave_SecretChamber_B4F_Text_NataliePostTeach::
	.string "So now, I suppose it's your time to\n"
	.string "go on to the last fight before you\l"
	.string "can face our leader.\p"
	.string "But first, please allow me to heal\n"
	.string "your living teammates.\p"
	.string "……… ………\p"
	.string "Or actually, it's funnier if I don't.\p"
	.string "I told you I like to play tricks!\n"
	.string "Good luck with Olivia!$"
