SafariZone_SecretHouse_Text_CongratsYouveWon::
    .string "Ah! Finally!\p"
    .string "You're the first person to reach\n"
    .string "the SECRET HOUSE!\p"
    .string "Although I made a campaign\n"
    .string "for our grand opening,\p"
    .string "I was getting worried that no one\n"
    .string "would win our campaign prize.\p"
    .string "Congratulations!\n"
    .string "You have won!$"

SafariZone_SecretHouse_Text_ReceivedTR99FromAttendant::
    .string "{PLAYER} received TR99\n"
    .string "from the attendant!$"

SafariZone_SecretHouse_Text_ExplainTR99::
    .string "TR99 is SKETCH.\p"
    .string "POKéMON will be able to learn any\n"
    .string "move by permanently copying the\l"
    .string "last move used on them.\p"
    .string "You're super lucky for winning this\n"
    .string "fabulous prize!$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize::
    .string "You don't have room for this\n"
    .string "fabulous prize!$"

