

CeruleanCave_SecretChamber_B2F_Text_LilithIntro::
	.string "Hi there.\n"
	.string "I'm LILITH.\p"
	.string "I'm known as LITTLE LILITH because\n"
	.string "I like to use N.F.E. POKéMON.\p"
	.string "In case you didn't already know, NFE\n"
	.string "stands for ''Not Fully Evolved''.\p"
	.string "In other words, they're nymphs!\n"
	.string "Babies! You wouldn't harm a baby,\l"
	.string "would you?\p"
	.string "But even though we're young, we can\n"
	.string "still handle ourselves!\p"
	.string "At least when it comes to POKéMON\n"
	.string "battles.\p"
	.string "We'll show you!$"

@ After you've defeated LILITH, but not yet AMY:
CeruleanCave_SecretChamber_B2F_Text_LilithRematchIntro::
	.string "Welcome back. Are you ready to\n"
	.string "try again? Let's go!$"

@ After you've defeated AMY:
CeruleanCave_SecretChamber_B2F_Text_LilithRematch2Intro::
	.string "Welcome back. Let's go!$"

CeruleanCave_SecretChamber_B2F_Text_LilithDefeat::
	.string "Oopsies!$"

CeruleanCave_SecretChamber_B2F_Text_LilithPostBattle::
	.string "You hurt my babies!\p"
	.string "But that's ok because I can just\n"
	.string "resurrect them again! Tee-hee!\p"
	.string "Well I suppose this means you've\n"
	.string "made it to MOLLY.\p"
	.string "But before you go, please allow me\n"
	.string "to heal your living teammates.$"

CeruleanCave_SecretChamber_B2F_Text_ShopIntro::
	.string "Also, I have a few things for sale\n"
	.string "that might interest you.\p"
	.string "Take a look, but be warned that I\n"
	.string "won't offer these wares to you\l"
	.string "again until you beat me again.$"

CeruleanCave_SecretChamber_B2F_Text_ShopOutro::
	.string "Don't forget, if you leave this cave\n"
	.string "you will have to start all over!\p"
	.string "I'm going to go on ahead and then\n"
	.string "I'll see you in the final chamber\l"
	.string "should you make it that far.\p"
	.string "Good luck!$"
