

CeruleanCave_SecretChamber_B2F_Text_LilithIntro::
	.string "Hey there.\n"
	.string "I'm LILITH.\p"
	.string "I'm known as LITTLE LILITH because\n"
	.string "I like to use NFE POKéMON.\p"
	.string "In case you didn't already know, NFE\n"
	.string "stands for ''Not Fully Evolved''.$"

@ After you've defeated LILITH, but not yet AMY:
CeruleanCave_SecretChamber_B2F_Text_LilithRematchIntro::
	.string "Welcome back. Are you ready to\n"
	.string "try again? Let's go!$"

@ After you've defeated AMY:
CeruleanCave_SecretChamber_B2F_Text_LilithRematch2Intro::
	.string "Welcome back. Let's go!$"

CeruleanCave_SecretChamber_B2F_Text_LilithDefeat::
	.string "Oopsies!$"

CeruleanCave_SecretChamber_B2F_Text_LilithPostBattle::
	.string "But first, please allow me to heal\n"
	.string "your living teammates.$"

CeruleanCave_SecretChamber_B2F_Text_ShopIntro::
	.string "I have a few things for sale that\n"
	.string "might interest you.\p"
	.string "Take a look, but be warned that I\n"
	.string "won't offer these wares to you\l"
	.string "again until you beat me again.$"

CeruleanCave_SecretChamber_B2F_Text_ShopOutro::
	.string "Don't forget, if you leave this cave\n"
	.string "you will have to start all over!\p"
	.string "I'm going to go on ahead and then\n"
	.string "I'll see you in the final chamber\l"
	.string "should you make it that far.\p"
	.string "Good luck!$"
