#ifndef GUARD_CONSTANTS_GAME_MODES_H
#define GUARD_CONSTANTS_GAME_MODES_H

#define GAME_MODE_STANDARD      0
#define GAME_MODE_LIMITED       1
#define GAME_MODE_NUZLOCKE      2
#define GAME_MODE_ESCAPE_ROOM 129

#endif // GUARD_CONSTANTS_GAME_MODES_H
