Trade_Text_LookingToMixUpMyTeamWannaTradeForMon::
	.string "I'm trying to mix up my team…\n"
	.string "I'll take any new POKéMON.\p"
	.string "Wanna trade something for my\n"
	.string "{STR_VAR_2}?$"

Trade_Text_AwwOhWell::
	.string "Awww!\n"
	.string "Oh, well…$"

Trade_Text_WhatThatsNoMon::
	.string "What?\n"
	.string "That's no {STR_VAR_1}!$"

Trade_Text_HeyThanks::
	.string "Hey, thanks!$"

Trade_Text_IsntMyOldMonGreat::
	.string "Isn't my old {STR_VAR_2} great?$"

Trade_Text_LookingForSomethingSpecificWannaTradeForMon::
	.string "I'm looking for something\n"
	.string "specific: I'll trade my best\l"
	.string "POKéMON for a ''!'' UNOWN.\p"
	.string "Wanna trade one for my\n"
	.string "{STR_VAR_2}?$"

Trade_Text_LookingForSomethingSpecificWrongMon::
	.string "That's not a ''!'' UNOWN!$"

Trade_Text_WellIfYouDontWantTo::
	.string "Well, if you don't want to…$"

Trade_Text_ThisIsntMon::
	.string "Hmmm?\n"
	.string "This isn't a {STR_VAR_1}.\p"
	.string "Think of me if you get one.$"

Trade_Text_Thanks::
	.string "Thanks!$"

Trade_Text_HasTradedMonGrownStronger::
	.string "The {STR_VAR_2} that I traded you,\n"
	.string "has it grown stronger?$"

Trade_Text_ThatsTooBad::
	.string "That's too bad.$"

Trade_Text_ThisIsNoMon::
	.string "…This is no {STR_VAR_1}.\p"
	.string "If you get one, trade it with me.$"

Trade_Text_ThanksYoureAPal::
	.string "Thanks, you're a pal!$"

Trade_Text_HowIsMyOldMon::
	.string "How is my old {STR_VAR_2}?\n"
	.string "My {STR_VAR_1} is doing great!$"
