gOtherText_NewName::
    .string "NEW NAME$"

gNameChoice_Green::
    .string "Green$"

gNameChoice_Red::
    .string "Red$"

gNameChoice_Leaf::
    .string "Leaf$"

gNameChoice_Fire::
    .string "Fire$"

gNameChoice_Gary::
    .string "Gary$"

gNameChoice_Kaz::
    .string "Kaz$"

gNameChoice_Toru::
    .string "Toru$"

gNameChoice_Ash::
    .string "Ash$"

gNameChoice_Kene::
    .string "Kene$"

gNameChoice_Geki::
    .string "Geki$"

gNameChoice_Jak::
    .string "Jak$"

gNameChoice_Janne::
    .string "Janne$"

gNameChoice_Jonn::
    .string "Jonn$"

gNameChoice_Kamon::
    .string "Kamon$"

gNameChoice_Karl::
    .string "Karl$"

gNameChoice_Taylor::
    .string "Taylor$"

gNameChoice_Oscar::
    .string "Oscar$"

gNameChoice_Hiro::
    .string "Hiro$"

gNameChoice_Max::
    .string "Max$"

gNameChoice_Jon::
    .string "Jon$"

gNameChoice_Ralph::
    .string "Ralph$"

gNameChoice_Kay::
    .string "Kay$"

gNameChoice_Tosh::
    .string "Tosh$"

gNameChoice_Roak::
    .string "Roak$"

gNameChoice_Omi::
    .string "Omi$"

gNameChoice_Jodi::
    .string "Jodi$"

gNameChoice_Amanda::
    .string "Amanda$"

gNameChoice_Hillary::
    .string "Hillary$"

gNameChoice_Makey::
    .string "Makey$"

gNameChoice_Michi::
    .string "Michi$"

gNameChoice_Paula::
    .string "Paula$"

gNameChoice_June::
    .string "June$"

gNameChoice_Cassie::
    .string "Cassie$"

gNameChoice_Rey::
    .string "Rey$"

gNameChoice_Seda::
    .string "Seda$"

gNameChoice_Kiko::
    .string "Kiko$"

gNameChoice_Mina::
    .string "Mina$"

gNameChoice_Norie::
    .string "Norie$"

gNameChoice_Sai::
    .string "Sai$"

gNameChoice_Momo::
    .string "Momo$"

gNameChoice_Suzi::
    .string "Suzi$"

gControlsGuide_Text_NuzlockeIntro::
    .string "Nuzlocke info:\n\n"
    .string "In a moment, you will be asked to\n"
    .string "choose between STANDARD and NUZLOCKE\n"
    .string "modes. Here is what NUZLOCKE means:$"

gControlsGuide_Text_NuzlockeInfo1::
    .string "1. When a POKéMON faints, it dies.\n"
    .string "   Neither a POKéMON CENTER nor any\n"
    .string "   REVIVE-like item will revive it.$"

gControlsGuide_Text_NuzlockeInfo2::
    .string "2. You can catch only one POKéMON\n"
    .string "   per area. After you do, they\n"
    .string "   will stop spawning there forever.$"

gControlsGuide_Text_NuzlockeInfo3::
    .string "3. Some additional changes will\n"
    .string "   be made as well, e.g. some items\n"
    .string "   will not be usable in battle.$"

gControlsGuide_Text_NuzlockeInfo4::
    .string "4. Feel free to place additional\n"
    .string "   restrictions on yourself for\n"
    .string "   added challenge!$"

gControlsGuide_Text_Intro::
    .string "The various buttons will be explained in\n"
    .string "the order of their importance.$"

gControlsGuide_Text_DPad::
    .string "Moves the main character.\n"
    .string "Also used to choose various data\n"
    .string "headings.$"

gControlsGuide_Text_AButton::
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"

gControlsGuide_Text_BButton::
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"

gControlsGuide_Text_StartButton::
    .string "Press this button to open the\n"
    .string "MENU.$"

gControlsGuide_Text_SelectButton::
    .string "Used to shift items and to use\n"
    .string "a registered item.$"

gControlsGuide_Text_LRButtons::
    .string "If you need help playing the\n"
    .string "game, or on how to do things,\n"
    .string "press the L or R Button.$"

gOakSpeech_Text_AskGameType::
    .string "What type of game do you want to\n"
    .string "play?$"

gOakSpeech_Text_AskPlayerGender::
    .string "Now tell me.\n"
    .string "How do you identify?$"

gPikachuIntro_Text_Page1::
    .string "Tips (for both modes):\n"
    .string "\n"
    .string "1. SAVE OFTEN! While I have done my\n"
    .string "   best to eliminate as many bug as I\n"
    .string "   can, it is possible that I missed\n"
    .string "   something, and it would sure suck if\n"
    .string "   the game crashed and you lost all\n"
    .string "   your progress! Please save often!$"

gPikachuIntro_Text_Page2::
    .string "2. Check every POKéMART. Many shops\n"
    .string "   have new or changed selections.\n"
    .string "\n"
    .string "3. Pick up item balls and look for\n"
    .string "   hidden items. Many are different.\n"
    .string "\n"
    .string "4. Many side quests are now optional,\n"
    .string "   so feel free to skip them!$"

gPikachuIntro_Text_Page3::
    .string "5. TMs are reusable. Don't forget to\n"
    .string "   make use of them! TRs are not.\n"
    .string "\n"
    .string "6. ESCAPE ROPE is reusable. Buy one!\n"
    .string "\n"
    @string "people in need, overcoming challenges,\n"
    .string "7. \n"
    .string "\n"
    .string "8. Most importantly: Have fun!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Hello, there!\n"
    .string "Glad to meet you!\p"
    .string "Welcome to the world of POKéMON!\p"
    .string "My name is OAK.\p"
    .string "People affectionately refer to me\n"
    .string "as the POKéMON PROFESSOR.\p$"

gOakSpeech_Text_ThisWorld::
    .string "This world…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "…is inhabited far and wide by\n"
    .string "creatures called POKéMON.\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "For some people, POKéMON are pets.\n"
    .string "Others use them for battling.\p"
    .string "As for myself…\p"
    .string "I study POKéMON as a profession.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "But first, tell me a little about\n"
    .string "yourself.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Let's begin with your name.\n"
    .string "What is it?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Right…\n"
    .string "So your name is {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
    .string "This is my grandson.\p"
    .string "He's been your rival since you both\n"
    .string "were babies.\p"
    .string "…Erm, what was his name now?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "Your rival's name, what was it now?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "…Er, was it {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "That's right! I remember now!\n"
    .string "His name is {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "Your very own POKéMON legend is\n"
    .string "about to unfold!\p"
    .string "A world of dreams and adventures\n"
    .string "with POKéMON awaits! Let's go!$"
