SaffronCity_House_Text_DontLookAtMyLetter::
    .string "…Thank you for writing.\n"
    .string "I hope to see you soon!\p"
    .string "…Hey!\n"
    .string "Don't look at my letter!$"

SaffronCity_House_Text_Pidgey::
    .string "PIDGEY: Kurukkoo!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
    .string "The COPYCAT is cute!\p"
    .string "She bit me and I kind of liked it…\p"
    .string "I'm getting her a POKé DOLL!$"

SaffronCity_House_Text_ExplainPPUp::
    .string "I was given a PP UP as a gift.\p"
    .string "It's used to increase the PP of\n"
    .string "a POKéMON's move.\p"
    .string "I should use it on a powerful move\n"
    .string "with only a few PP.\p"
    .string "I like PP UP because it makes my PP\n"
    .string "bigger.\p"
    .string "I heard there's another item called\n"
    .string "PP MAX that makes your PP huge!\p"
    .string "I should buy some for my boyfriend.$"

