Route4_Text_TrippedOverGeodude::
    .string "Ouch! I tripped over a rocky\n"
    .string "POKéMON, GEODUDE!$"

Route4_Text_CrissyIntro::
    .string "I came to MT. MOON in search of\n"
    .string "mushroom POKéMON.$"

Route4_Text_CrissyDefeat::
    .string "After all I did to catch them!$"

Route4_Text_CrissyPostBattle::
    .string "There might not be any more\n"
    .string "mushrooms here.\p"
    .string "I think I got them all.$"

Route4_Text_MtMoonEntrance::
    .string "MT. MOON\n"
    .string "Tunnel Entrance$"

Route4_Text_RouteSign::
    .string "ROUTE 4\n"
    .string "MT. MOON - CERULEAN CITY$"

Text_MegaPunchTeach::
    .string "A sweet and delicate kiss!\p"
    .string "Packed with love and kindness!\p"
    .string "When the chips are down,\n"
    .string "SWEET KISS is the ultimate kiss!\l"
    .string "You agree, yes?\p"
    .string "Now!\n"
    .string "Let me teach it to your POKéMON!$"

Text_MegaPunchDeclined::
    .string "You'll be back when you understand\n"
    .string "the worth of SWEET KISS.$"

Text_MegaPunchWhichMon::
    .string "Fine!\n"
    .string "Which POKéMON will learn it?$"

Text_MegaPunchTaught::
    .string "Now, we are comrades in the way of\n"
    .string "kissing!\p"
    .string "You should go before you're seen\n"
    .string "by the misguided fool who trains\l"
    .string "his silly lips over there.$"

Text_MegaKickTeach::
    .string "A lovely and romantic kiss!\p"
    .string "Packed with love and warmth!\p"
    .string "When you get right down to it,\n"
    .string "LOVELY KISS is the ultimate kiss!\l"
    .string "Don't you agree?\p"
    .string "Okay!\n"
    .string "I'll teach it to your POKéMON!$"

Text_MegaKickDeclined::
    .string "You'll come crawling back when you\n"
    .string "realize the value of LOVELY KISS.$"

Text_MegaKickWhichMon::
    .string "All right!\n"
    .string "Which POKéMON wants to learn it?$"

Text_MegaKickTaught::
    .string "Now, we are soul mates in the way\n"
    .string "of kissing!\p"
    .string "You should run before you're seen\n"
    .string "by the deluded nitwit who trains\l"
    .string "only simple kissing over there.$"

Route4_Text_PeopleLikeAndRespectBrock::
    .string "Oh, wow, that's the BOULDERBADGE!\n"
    .string "You got it from BROCK, didn't you?\p"
    .string "BROCK is cool. He's not just tough.\n"
    .string "People like and respect him.\p"
    .string "I want to become a GYM LEADER\n"
    .string "like him.$"
