IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "At the POKéMON LEAGUE, you will\n"
    .string "face the ELITE FOUR all in a row.\p"
    .string "If you lose, you have to start all\n"
    .string "over again!\p"
    .string "This is it!\n"
    .string "Go for it!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
    .string "From here on, you face the\n"
    .string "ELITE FOUR one by one.\p"
    .string "If you win, a door opens to the\n"
    .string "next TRAINER. Good luck!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string "I am so sorry, but you've wasted\n"
    .string "your time coming here.\p"
    .string "LORELEI of the ELITE FOUR is\n"
    .string "absent, you see.\p"
    .string "As a result, the POKéMON LEAGUE is\n"
    .string "closed for the time being.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .string "AGATHA's GHOST-type POKéMON are\n"
    .string "horrifically terrifying in toughness.\p"
    .string "I took my FIGHTING-type POKéMON\n"
    .string "and raised them to the max.\p"
    .string "I went at AGATHA feeling pretty\n"
    .string "confident, but she whupped us.\p"
    .string "That old lady's also got a really\n"
    .string "short fuse, too.\p"
    .string "It doesn't take anything to get\n"
    .string "that scary lady hollering.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
    .string "Maybe becoming an ELITE FOUR\n"
    .string "member is in the blood.\p"
    .string "From what I've heard, LANCE has\n"
    .string "a cousin who's a GYM LEADER\l"
    .string "somewhere far away.$"

IndigoPlateau_PokemonCenter_1F_Text_JulianaBeatEmilyFirst::
    .string "……… ………\p"
    .string "Go beat EMILY in CELADON CITY.$"

IndigoPlateau_PokemonCenter_1F_Text_JulianaIntro::
    .string "Hi……… I'm Juliana.\p"
    .string "……… ………\p"
    .string "Talking is hard for me.\p"
    .string "……… ………\p"
    .string "Battling is not.\p"
    .string "……… ………\n"
    .string "……… ………\p"
    .string "Good luck!$"

IndigoPlateau_PokemonCenter_1F_Text_JulianaRematchIntro::
    .string "……… ………\p"
    .string "Good luck!$"

IndigoPlateau_PokemonCenter_1F_Text_JulianaDefeat::
    .string "Nice!$"

IndigoPlateau_PokemonCenter_1F_Text_JulianaPostBattle::
    .string "Talk again for a rematch.$"

IndigoPlateau_PokemonCenter_1F_Text_JulianaPreTR100::
    .string "Oh!\p"
    .string "……… ………\n"
    .string "……… ………\p"
    .string "EMILY probably gave you one of\n"
    .string "these already……… but here.$"

IndigoPlateau_PokemonCenter_1F_Text_JulianaGotTR100::
    .string "{PLAYER} received TR100\n"
    .string "from JULIANA.$"

IndigoPlateau_PokemonCenter_1F_Text_JulianaPostTR100::
    .string "……… ………\p"
    .string "TR100 contains PHOENIX CALL.\p"
    .string "……… ………\p"
    .string "For resurrection.$"

