CeladonCity_GameCorner_Text_TakeCoinCase::
    .string "Welcome!\p"
    .string "I see you don't have a\n"
    .string "COIN CASE yet.$"

CeladonCity_GameCorner_Text_ReceivedCoinCaseFromInfoClerk::
    .string "{PLAYER} received a COIN CASE.$"

CeladonCity_GameCorner_Text_InfoClerkMakeRoomForThis::
    .string "If you make room for it, we'll\n"
    .string "give you one!$"

CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor::
    .string "Welcome!\p"
    .string "You can exchange your COINS for\n"
    .string "fabulous prizes next door.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins::
    .string "Welcome to ROCKET GAME CORNER!\p"
    .string "Do you need some game COINS?\n"
    .string "Would you like to buy some?$"

CeladonCity_GameCorner_Text_ComePlaySometime::
    .string "No?\n"
    .string "Please come play sometime!$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase::
    .string "Oh, I'm sorry.\n"
    .string "You don't have a COIN CASE.$"

CeladonCity_GameCorner_Text_CoinCaseIsFull::
    .string "Whoops!\n"
    .string "Your COIN CASE is full.$"

CeladonCity_GameCorner_Text_CantAffordCoins::
    .string "You can't afford the COINS.$"

CeladonCity_GameCorner_Text_HereAreYourCoins::
    .string "Thank you.\n"
    .string "Here are your COINS!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace::
    .string "Keep this quiet.\p"
    .string "It's rumored that this place is run\n"
    .string "by TEAM ROCKET.\p"
    .string "And another rumor: It's possible to\n"
    .string "cheat at the slots somehow!$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds::
    .string "I think these machines have\n"
    .string "different odds.\p"
    .string "If only there was a way to\n"
    .string "know which icons will show up.$"

CeladonCity_GameCorner_Text_DoYouWantToPlay::
    .string "Kid, do you want to play?\p"
    .string "I heard you can cheat at the\n"
    .string "slots using some sort of device.$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan::
    .string "{PLAYER} received 10 COINS\n"
    .string "from the man.$"

CeladonCity_GameCorner_Text_DontNeedMyCoins::
    .string "You don't need my COINS!$"

CeladonCity_GameCorner_Text_WinsComeAndGo::
    .string "Wins seem to come and go.\n"
    .string "Nothing's a sure thing.\p"
    .string "I wish I knew how to cheat.$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck::
    .string "These slot games…\n"
    .string "Win or lose, it's only by luck.\p"
    .string "If only there was some way to\n"
    .string "make winning more likely…$"

CeladonCity_GameCorner_Text_GymGuyAdvice::
    .string "Hey!\p"
    .string "You have better things to do,\n"
    .string "champ in the making!\p"
    .string "CELADON GYM's LEADER is ERIKA.\p"
    .string "She is a user of GRASS-type\n"
    .string "POKéMON, and at one with nature.\p"
    .string "She might appear docile because of\n"
    .string "her flower arranging…\p"
    .string "But she's not one to be taken\n"
    .string "lightly!$"

CeladonCity_GameCorner_Text_RareMonsForCoins::
    .string "They offer rare POKéMON that can\n"
    .string "be exchanged for your COINS.\p"
    .string "But, I just can't seem to win!\n"
    .string "Maybe there's a way to cheat…$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked::
    .string "Games are scary!\n"
    .string "It's so easy to get hooked!\p"
    .string "But I heard there's a device that\n"
    .string "can help you win more often!$"

CeladonCity_GameCorner_Text_WantSomeCoins::
    .string "What's up?\n"
    .string "Want some COINS?\p"
    .string "I heard you can cheat at these\n"
    .string "slot machines somehow.$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy::
    .string "{PLAYER} received 20 COINS\n"
    .string "from the nice guy.$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins::
    .string "You have lots of COINS!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant::
    .string "Darn! I need more COINS for the\n"
    .string "POKéMON I want!\p"
    .string "How do you do the cheat?\n"
    .string "Do you know?$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo::
    .string "Hey, what? I'm trying to figure out\n"
    .string "how to cheat, so shoo!\p"
    .string "Here's some coins, now leave me\n"
    .string "alone!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan::
    .string "{PLAYER} received 20 COINS\n"
    .string "from the man.$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins::
    .string "You've got plenty of your own\n"
    .string "COINS!$"

CeladonCity_GameCorner_Text_WatchReelsClosely::
    .string "The trick is to watch the reels\n"
    .string "closely… or cheat, if possible!$"

CeladonCity_GameCorner_Text_GruntIntro::
    .string "I'm guarding this poster!\n"
    .string "Go away, or else!$"

CeladonCity_GameCorner_Text_GruntDefeat::
    .string "Dang!$"

CeladonCity_GameCorner_Text_GruntPostBattle::
    .string "The TEAM ROCKET HIDEOUT might\n"
    .string "be discovered!\p"
    .string "I better tell BOSS!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
    .string "Hey!\p"
    .string "A switch behind the poster!?\n"
    .string "Let's push it!$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired::
    .string "A COIN CASE is required…$"

CeladonCity_GameCorner_Text_DontHaveCoinCase::
    .string "Oops!\n"
    .string "Don't have the COIN CASE!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
    .string "A slot machine!\n"
    .string "Want to play?$"

CeladonCity_GameCorner_Text_SilphScopeRevealsSlots::
    .string "The SILPH SCOPE reveals the\n"
    .string "reels and guides your hand.$"

CeladonCity_GameCorner_Text_OutOfOrder::
    .string "OUT OF ORDER\n"
    .string "This is broken.$"

CeladonCity_GameCorner_Text_OutToLunch::
    .string "OUT TO LUNCH\n"
    .string "This is reserved.$"

CeladonCity_GameCorner_Text_SomeonesKeys::
    .string "Someone's keys!\n"
    .string "They'll be back.$"

