EscapeRoom_Text_AntiSoftLock_PreFix::
    .string "OAK: Hi, I'm here to fix any soft-\n"
    .string "locks you may encounter.$"

EscapeRoom_Text_AntiSoftLock_PostFix::
    .string "I only checked your party, not\n"
    .string "your PC… but as for your party,\l"
    .string "you should now be good to go!$"

EscapeRoom_Text_Sign_JustADecoration::
    .string "This is just a decoration.\p"
    @ Fallthrough
EscapeRoom_Text_Sign_NoHiddenItems::
    .string "There are no invisible items.\p"
    .string "Stop looking for hidden items!$"

EscapeRoom_Text_Sign1::
    .string "Welcome to Amy's Escape Room!\p"

    .string "First of all, I tried very hard\n"
    .string "to make this mode deterministic.\p"

    .string "Random critical hits, accuracy,\n"
    .string "etc. have been completely removed.\p"

    .string "If you should happen to get soft-\n"
    .string "locked, see Prof. Oak for a fix.\p"

    .string "It's mostly gen 9 mechanics, but\n"
    .string "some things may be different.\p"

    .string "For instance, you can keep items\n"
    .string "you steal from trainers' POKéMON.\p"

    .string "I tried to limit the hack-specific\n"
    .string "features used in this mode so that\l"
    .string "POKéMON knowledge matters more.\p"

    .string "A few new items are exceptions to\n"
    .string "this and have custom behaviors.\p"

    .string "Poké Balls have been altered, too.\p"

    .string "There's only one wild POKéMON per\n"
    .string "encounter method per location,\p"
    .string "so, say you encounter a wild\n"
    .string "Bidoof by walking in the grass,\l"
    .string "that grass will only have Bidoof.\p"

    .string "You should only ever catch one of\n"
    .string "any POKéMON species.\p"

    .string "All findable items in the game\n"
    .string "are in item balls (i.e. not hidden).\p"

    .string "If you talk to a trainer again\n"
    .string "after beating them, you can refight\l"
    .string "them, which is usually a bad idea.\p"

    .string "Note that if you manage to piss off\n"
    .string "a trainer REAL bad, they leave.\p"

    .string "Remember, luck has been removed\n"
    .string "where possible. So it doesn't make\l"
    .string "much sense to wish you luck…\p"

    .string "Therefore, break a leg!$"


EscapeRoom_Text_Sign2::
    .string "This looks like a great spot\n"
    .string "to catch a fish!$"

EscapeRoom_Text_Sign3::
    .string "Please don't CUT my special\n"
    .string "little tree!$"

EscapeRoom_Text_Sign4::
    .string "Push the boulder onto the switch\n"
    .string "to make the ROCKET GRUNT lose his\l"
    .string "special Rocket Balls.$"

EscapeRoom_Text_DoorIsLocked::
    .string "The door is locked…$"

EscapeRoom_Text_MoveTutor_Trick_RareCandy_Message::
    .string "Hey, do you want some candy?$"

EscapeRoom_Text_MoveTutor_Trick_RareCandy_Received::
    .string "{PLAYER} received RARE CANDY!$"

EscapeRoom_Text_MoveTutor_Trick_SuperRod_Message::
    .string "And here, you can take my rod.$"

EscapeRoom_Text_MoveTutor_Trick_SuperRod_Received::
    .string "{PLAYER} received SUPER ROD!$"

EscapeRoom_Text_TrickTeach::
    .string "I can do TRICKs real good.\p"
    .string "Want me to teach it to one of your\n"
    .string "POKéMON?$"

EscapeRoom_Text_TrickWhichMon::
    .string "Which POKéMON will learn TRICK?$"

EscapeRoom_Text_TrickDeclined::
    .string "Aww.$"

EscapeRoom_Text_TrickTaught::
    .string "Yay!$"

EscapeRoom_Text_ANotEnoughPkmn::
    .string "You're pretty sneaky to get\n"
    .string "past us like that…\p"
    .string "But I don't think you can beat the\n"
    .string "next trainer with only one POKéMON…$"

EscapeRoom_Text_AIntro::
    .string "Ash: You'll have to find a clever\n"
    .string "way past us, as we're tough!\p"
    .string "Zoe: That's right! We're tough!$"

EscapeRoom_Text_ADefeat::
    .string "Ash: Nooooooo!!$"

EscapeRoom_Text_BIntro::
    .string "If you can't beat me, try talking\n"
    .string "to the twins you passed for a hint.$"

EscapeRoom_Text_BDefeat::
    .string "Incredible!$"

EscapeRoom_Text_CIntro::
    .string "If you get stuck, count my HOPPIP.$"

EscapeRoom_Text_CDefeat::
    .string "You counted them well alright!$"

EscapeRoom_Text_SittingBoy_NeedSomethingToWakeUp::
    .string "I'm eepy… If only I had something\n"
    .string "to help me wake up…$"

EscapeRoom_Text_SittingBoy_IDontLikeCandy::
    .string "I was given candy by someone but I\n"
    .string "don't like candy. Do you want it?$"

EscapeRoom_Text_SittingBoy_RareCandy_Received::
    .string "{PLAYER} received RARE CANDY!$"

EscapeRoom_Text_SittingBoy_GiveCocaine::
    .string "Give “Coffee” to the child?$"

EscapeRoom_Text_SittingBoy_YayCocaine::
    .string "Yay, drugs!$"

EscapeRoom_Text_SittingBoy_PleaseFindMeSomethingEnergizing::
    .string "Please find me something energizing!$"

EscapeRoom_Text_TrainerDWontFightBeforeBoulderPuzzleSolved::
    .string "Hey kid, have you seen my balls?$"

EscapeRoom_Text_TrainerDShitILostMyBalls::
    .string "Shit, I lost my balls…\n"
    .string "Have you seen them?$"

EscapeRoom_Text_TrainerDWontFightPartialParty::
    .string "Hold on, you don't have a full\n"
    .string "team of 6 POKéMON in your party.\p"
    .string "I may be a ROCKET, but I'm also\n"
    .string "honorable, and won't fight you\p"
    .string "unless you have as many POKéMON\n"
    .string "with you as I have…\l"
    .string "It's only fair that way!$"

EscapeRoom_Text_DIntro::
    .string "Alright, I see you have a full\n"
    .string "team of 6 POKéMON in your party!\p"
    .string "Let's do this!$"

EscapeRoom_Text_DDefeat::
    .string "Damn bad day…\p"
    .string "First I lose my balls, then I lose\n"
    .string "a fight to a kid…\p"
    .string "I've got it! I know what would turn\n"
    .string "my day around!\p"
    .string "All your POKéMON are mine now!\p"
    .string "I'll leave you with a single one.$"

EscapeRoom_Text_DTookPokemon::
    .string "The ROCKET GRUNT stole all your\n"
    .string "POKéMON but RALTS!$"

EscapeRoom_Text_DPostTakePokemon::
    .string "And now I make my getaway! SEE YA!$"

EscapeRoom_Text_EIntro::
    .string "I'm in the way, but simply beating\n"
    .string "me won't be enough to get me to go…$"

EscapeRoom_Text_EDefeat::
    .string "Oof!$"

EscapeRoom_Text_FIntro::
    .string "I'm a fan of OHKOs…\p"
    .string "I bet you wish you still had your\n"
    .string "SUDOWOODO or your SHUCKLE!$"

EscapeRoom_Text_FDefeat::
    .string "Wow!$"

EscapeRoom_Text_GIntro::
    .string "Intro…$"

EscapeRoom_Text_GDefeat::
    .string "Defeat…$"

EscapeRoom_Text_HIntro::
    .string "Intro…$"

EscapeRoom_Text_HDefeat::
    .string "Defeat…$"

EscapeRoom_Text_PsyduckIntro::
    .string "PSYDUCK: Quack…$"

EscapeRoom_Text_PsyduckDefeat::
    .string "PSYDUCK: Quack…$"

EscapeRoom_Text_YouBastard::
    .string "You bastard.$"

EscapeRoom_Text_YouJerk::
    .string "You jerk.$"
