

CeruleanCave_SecretChamber_B9F_Text_Kyouko::
	.string "KYOUKO: Kyouko-kyun!\p"
	.string "I believe in you, cutie!$"

CeruleanCave_SecretChamber_B9F_Text_Lilith::
	.string "LILITH: What will I do if you win?\p"
	.string "I'm open to suggestions!$"

CeruleanCave_SecretChamber_B9F_Text_Molly::
	.string "MOLLY: Hurry up and get the fight\n"
	.string "over with so I can have a shower!$"

CeruleanCave_SecretChamber_B9F_Text_Natalie::
	.string "NATALIE: You just lost “THE GAME”!$"

CeruleanCave_SecretChamber_B9F_Text_Olivia::
	.string "OLIVIA: I'll be watching this fight\n"
	.string "closely, godslayer.$"

CeruleanCave_SecretChamber_B9F_Text_AmyIntro::
	.string "Hi! I'm AMY.\p"
	.string "Do you like POKéMON?\p"
	.string "I suppose you wouldn't be here if\n"
	.string "you didn't.\p"
	.string "I love POKéMON. I've been a huge\n"
	.string "fan since my early childhood.\p"
	.string "Who's your favorite POKéMON?\p"
	.string "I have a lot of favorites, but if I\n"
	.string "had to choose just one… …then by\l"
	.string "appearance it's got to be GENGAR.\p"
	.string "I always name my GENGAR “Hugs”.\p"
	.string "But I haven't brought Hugs here to\n"
	.string "battle you today.\p"
	.string "Why?\n"
	.string "You'll see.\p"
	.string "Are you ready to get your ass beat\n"
	.string "by the girl who made this hack?\p"
	.string "Well, then. As leader of the\n"
	.string "ULTIMATE CUTIES and the developer\p"
	.string "of this hack… I, AMY, present to\n"
	.string "you one final challenge. Let's go!$"

@ After you've defeated AMY:
CeruleanCave_SecretChamber_B9F_Text_AmyRematchIntro::
	.string "Welcome back. Let's go!$"

CeruleanCave_SecretChamber_B9F_Text_AmyDefeat::
	.string "You did it!$"

CeruleanCave_SecretChamber_B9F_Text_AmyPostBattle::
	.string "So…\p"
	.string "How did you like my ROM hack?\n"
	.string "I worked awfully hard on it.\p"
	.string "I would like to thank the devs\n"
	.string "and contributors for the following\l"
	.string "upstream projects:\p"
	.string "pret/pokefirered\n"
	.string "rh-hideout/pokeemerald-expansion\p"
	.string "Sotomura/pokefirered-rtc\n"
	.string "cawtds/pokefirered-expansion\p"
	.string "This project would not have been\n"
	.string "possible without their hard work.\p"
	.string "I hope you had as much fun playing\n"
	.string "as I had working on this project.\p"
	.string "Until next time!$"
