

CeruleanCave_SecretChamber_B9F_Text_Kyouko::
	.string "Kyouko.$"

CeruleanCave_SecretChamber_B9F_Text_Lilith::
	.string "Lilith.$"

CeruleanCave_SecretChamber_B9F_Text_Molly::
	.string "Molly.$"

CeruleanCave_SecretChamber_B9F_Text_Natalie::
	.string "Natalie.$"

CeruleanCave_SecretChamber_B9F_Text_Olivia::
	.string "Olivia.$"

CeruleanCave_SecretChamber_B9F_Text_AmyIntro::
	.string "Intro.$"

@ After you've defeated AMY, but not yet AMY:
CeruleanCave_SecretChamber_B9F_Text_AmyRematchIntro::
	.string "Welcome back. Are you ready to\n"
	.string "try again? Let's go!$"

@ After you've defeated AMY:
CeruleanCave_SecretChamber_B9F_Text_AmyRematch2Intro::
	.string "Welcome back. Let's go!$"

CeruleanCave_SecretChamber_B9F_Text_AmyDefeat::
	.string "Nicely done.$"

CeruleanCave_SecretChamber_B9F_Text_AmyPostBattle::
	.string "But first, please allow me to heal\n"
	.string "your living teammates.$"

CeruleanCave_SecretChamber_B9F_Text_AmyPostHeal::
	.string "Since you beat me, I'll teach it\n"
	.string "to one of your POKéMON if you like.\p"
	.string "This isn't a one-time offer, either,\n"
	.string "but you'll have to beat me again\l"
	.string "before I'll teach it again.$"

CeruleanCave_SecretChamber_B9F_Text_AmyTeach::
	.string "Shall I teach Mail Script to one of\n"
	.string "your POKéMON?$"

CeruleanCave_SecretChamber_B9F_Text_AmyWhichMon::
	.string "Who should learn Mail Script?$"

CeruleanCave_SecretChamber_B9F_Text_AmyPostTeach::
	.string "Now, a word of caution before you\n"
	.string "move on: If you leave this cave,\l"
	.string "you will have to start all over!\p"
	.string "I'm going to go on ahead and then\n"
	.string "I'll see you in the final chamber\l"
	.string "should you make it that far.\p"
	.string "Good luck, and stay cute!$"


