

CeruleanCave_SecretChamber_B5F_Text_OliviaIntro::
	.string "“Olympian” means godlike, omnipotent,\n"
	.string "omniscient.\p"
	.string "Olympian Olivia is all of these\n"
	.string "things.\p"
	.string "Are you ready to see what a god can\n"
	.string "achieve?\p"
	.string "Bow to me!$"

@ After you've defeated OLIVIA, but not yet AMY:
CeruleanCave_SecretChamber_B5F_Text_OliviaRematchIntro::
	.string "Welcome back. Are you ready to\n"
	.string "try again? Let's go!$"

@ After you've defeated AMY:
CeruleanCave_SecretChamber_B5F_Text_OliviaRematch2Intro::
	.string "Welcome back. Let's go!$"

CeruleanCave_SecretChamber_B5F_Text_OliviaDefeat::
	.string "Impossible!$"

CeruleanCave_SecretChamber_B5F_Text_OliviaPostBattle::
	.string "Please allow me to heal your living\n"
	.string "teammates.$"

CeruleanCave_SecretChamber_B5F_Text_OliviaPostHeal::
	.string "Go forth, godslayer.\n"
	.string "Our leader awaits.$"
