PokemonMansion_Text_PressSecretSwitch::
    .string "A secret switch!\p"
    .string "Press it?$"

PokemonMansion_Text_WhoWouldnt::
    .string "Who wouldn't?$"

PokemonMansion_Text_NotQuiteYet::
    .string "Not quite yet!$"

PokemonMansion_1F_Text_ArnieIntro::
    .string "I can't get out!\n"
    .string "This old place is one big puzzle.$"

PokemonMansion_1F_Text_ArnieDefeat::
    .string "Oh, no!\n"
    .string "My bag of loot!$"

PokemonMansion_1F_Text_ArniePostBattle::
    .string "The switches here open and close\n"
    .string "alternating sets of doors.$"

PokemonMansion_1F_Text_NewMonDiscoveredHidingUnderATruck::
    .string "Diary: July 5\n"
    .string "Opelucid City, Unova\p"
    .string "A new POKéMON was discovered\n"
    .string "hiding under a truck.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
    .string "Diary: July 10\n"
    .string "We named the newly discovered\l"
    .string "POKéMON ''MEW''.$"

