

CeruleanCave_SecretChamber_B1F_Text_KyoukoBeatEmilyFirst::
	.string "I'll fight you only after you have\n"
	.string "defeated both Emily and Juliana.\p"
	.string "Emily is first, and she can usually\n"
	.string "be found playing in CELADON CITY.$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoBeatJulianaFirst::
	.string "I'll fight you only after you have\n"
	.string "defeated Juliana.\p"
	.string "She can be often be found an the\n"
	.string "INDIGO PLATEAU POKéMON CENTER.$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoIntro::
	.string "Welcome to our SECRET HIDEOUT.\p"
	.string "We are the ULTIMATE CUTIES, a\n"
	.string "team of cute little girls who\p"
	.string "pose a final challenge to you on\n"
	.string "your journey.\p"
	.string "I am KYOUKO, the first in line.\p"
	.string "But just because I'm first, that\n"
	.string "doesn't mean I'm weak.\p"
	.string "Watch out for my wicked lead!$"

@ After you've defeated KYOUKO, but not yet AMY:
CeruleanCave_SecretChamber_B1F_Text_KyoukoRematchIntro::
	.string "Welcome back. Are you ready to\n"
	.string "try again? Let's go!$"

@ After you've defeated AMY:
CeruleanCave_SecretChamber_B1F_Text_KyoukoRematch2Intro::
	.string "Welcome back. Let's go!$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoDefeat::
	.string "Nicely done.$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoPostBattle::
	.string "Congratulations on winning the\n"
	.string "first fight! Let's see how you\l"
	.string "handle the rest of us.\p"
	.string "But first, please allow me to heal\n"
	.string "your living teammates.$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoPostHeal::
	.string "As you saw, we have access to new\n"
	.string "POKéMON, moves, abilities, items,\l"
	.string "and other mechanics.\p"
	.string "A powerful move called Mail Script\n"
	.string "allowed Courier to use several\l"
	.string "moves all at once.\p"
	.string "Since you beat me, I'll teach it\n"
	.string "to one of your POKéMON if you like.\p"
	.string "This isn't a one-time offer, either,\n"
	.string "but you'll have to beat me again\l"
	.string "before I'll teach it again.$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoTeach::
	.string "Shall I teach Mail Script to one of\n"
	.string "your POKéMON?$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoWhichMon::
	.string "Who should learn Mail Script?$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoPostTeach::
	.string "Now, a word of caution before you\n"
	.string "move on: If you leave this cave,\l"
	.string "you will have to start all over!\p"
	.string "I'm going to go on ahead and then\n"
	.string "I'll see you in the final chamber\l"
	.string "should you make it that far.\p"
	.string "Good luck, and stay cute!$"


