

CeruleanCave_SecretChamber_B1F_Text_KyoukoBeatEmilyFirst::
	.string "Beat Emily and Juliana first.$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoBeatJulianaFirst::
	.string "Beat Juliana first.$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoIntro::
	.string "Intro.$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoRematchIntro::
	.string "Rematch intro.$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoDefeat::
	.string "Defeat.$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoPostBattle::
	.string "Post battle.$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoPostHeal::
	.string "Post heal.$"


