

CeruleanCave_SecretChamber_B1F_Text_KyoukoBeatEmilyFirst::
	.string "I'll fight you only after you have\n"
	.string "defeated both Emily and Juliana.\p"
	.string "Emily is first, and she can usually\n"
	.string "be found playing in CELADON CITY.$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoBeatJulianaFirst::
	.string "I'll fight you only after you have\n"
	.string "defeated Juliana.\p"
	.string "She can be often be found an the\n"
	.string "INDIGO PLATEAU POKéMON CENTER.$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoIntro::
	.string "Welcome to our SECRET HIDEOUT.\p"
	.string "We are the ULTIMATE CUTIES, a\n"
	.string "team of young girls who pose a\p"
	.string "final challenge to you on your\n"
	.string "journey.\p"
	.string "I am KYOUKO, the first in line.\p"
	.string "But just because I'm first, that\n"
	.string "doesn't mean I'm weak.\p"
	.string "Some people affectionately call\n"
	.string "me ''CUTE KYOUKO''.\p"
	.string "This is because I only use cute\n"
	.string "POKéMON.\p"
	.string "Cute POKéMON can be strong too!\p"
	.string "I can't wait to show you my\n"
	.string "adorable little lovelies!\p"
	.string "Are you ready to meet them?$"

@ After you've defeated KYOUKO, but not yet AMY:
CeruleanCave_SecretChamber_B1F_Text_KyoukoRematchIntro::
	.string "Welcome back. Are you ready to\n"
	.string "try again? Let's go!$"

@ After you've defeated AMY:
CeruleanCave_SecretChamber_B1F_Text_KyoukoRematch2Intro::
	.string "Welcome back. Let's go!$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoDefeat::
	.string "Adorable!$"

CeruleanCave_SecretChamber_B1F_Text_KyoukoPostBattle::
	.string "Congratulations on winning the\n"
	.string "first fight! Let's see how you\l"
	.string "fare against the rest of us.\p"
	.string "But first, please allow me to heal\n"
	.string "your living teammates.$"

CeruleanCave_SecretChamber_B1F_Text_ShopIntro::
	.string "As you saw, we have access to new\n"
	.string "POKéMON, moves, abilities, items,\l"
	.string "and other mechanics.\p"
	.string "I have a few things for sale that\n"
	.string "might interest you.\p"
	.string "Take a look, but be warned that I\n"
	.string "won't offer these wares to you\l"
	.string "again until you beat me again.$"

CeruleanCave_SecretChamber_B1F_Text_ShopOutro::
	.string "Now, a word of caution before you\n"
	.string "move on: If you leave this cave,\l"
	.string "you will have to start all over!\p"
	.string "I'm going to go on ahead and then\n"
	.string "I'll see you in the final chamber\l"
	.string "should you make it that far.\p"
	.string "Good luck, and stay cute!$"

