PokemonLeague_ChampionsRoom_Text_Intro::
    .string "MOM: Hi, Honey.\p"
    .string "I heard you were on your way to\n"
    .string "face the POKéMON LEAGUE CHAMPION,\p"
    .string "and I couldn't miss the opportunity\n"
    .string "to be here to cheer you on!\p"
    .string "I was looking forward to seeing\n"
    .string "you here, {PLAYER}.\p"
    .string "You've collected all the badges\n"
    .string "and made it all the way to the\l"
    .string "POKéMON LEAGUE!\p"
    .string "And now…\p"
    .string "You're ready to face the CHAMPION!\p"
    .string "By the way, you know our neighbor,\n"
    .string "{RIVAL}? Well, he was here\p"
    .string "just a moment ago.  He was asking\n"
    .string "if you made it here first.\p"
    .string "I told him ''no'', but to expect to\n"
    .string "see you in no time.\p"
    .string "Oh, what's that?\n"
    .string "You want to know how he did\l"
    .string "against the CHAMPION?\p"
    .string "I'll tell you…\p"
    .string "I--your mother, and the reigning\n"
    .string "POKéMON LEAGUE CHAMPION,\l"
    .string "'crushed' him.\p"
    .string "I sent him home crying.\p"
    .string "Your MOM is the most powerful\n"
    .string "TRAINER in the world!\l"
    .string "Surprise, hun!$"

PokemonLeague_ChampionsRoom_Text_RematchIntro::
    .string "MOM: Hi, Honey!\p"
    .string "Ready for a rematch?\n"
    .string "I won't hold back this time!$"

PokemonLeague_ChampionsRoom_Text_Defeat::
    .string "NO!\n"
    .string "That can't be!\l"
    .string "You actually beat me!\p"
    .string "Congratulations, Honey!\n"
    .string "You're the the new CHAMPION!$"

PokemonLeague_ChampionsRoom_Text_Victory::
    .string "はーはッ！\n"
    .string "かった！　かった！　かった！\p"
    .string "{PLAYER}に　まける　ような\n"
    .string "おれさま　では　なーい！\p"
    .string "ま！　ポケモンの\n"
    .string "てんさい　{RIVAL}さま　あいてに\l"
    .string "ここまで　よく　がんばった！\p"
    .string "ほめて　つかわす！\n"
    .string "はーッ！　はーはッはッ！$"

PokemonLeague_ChampionsRoom_Text_PostBattle::
    .string "Congratulations again, Honey.$"

PokemonLeague_ChampionsRoom_Text_OakPlayer::
    .string "OAK: {PLAYER}!$"

PokemonLeague_ChampionsRoom_Text_OakCongratulations::
    .string "OAK: So, you've won!\n"
    .string "Sincerely, congratulations!\p"
    .string "You're the new POKéMON LEAGUE\n"
    .string "CHAMPION!\p"
    .string "You've grown up so much since you\n"
    .string "first left with {STR_VAR_1} to work\l"
    .string "on the POKéDEX.\p"
    .string "{PLAYER}, you have come of age!$"

PokemonLeague_ChampionsRoom_Text_OakImDisappointedRival::
    .string "OAK: {PLAYER}'s MOM…\n"
    .string "I'm disappointed in you.\p"
    .string "I thought I had trained you\n"
    .string "better than this.$"

PokemonLeague_ChampionsRoom_Text_OakAllowMeToHealPokemon::
    .string "OAK: {PLAYER}, your POKéMON look\n"
    .string "weary. Please, allow me to heal\l"
    .string "them for you.$"

PokemonLeague_ChampionsRoom_Text_OakPlayerComeWithMe::
    .string "OAK: {PLAYER}.\p"
    .string "You understand that your victory\n"
    .string "was not just your own doing.\p"
    .string "The bond you share with your\n"
    .string "POKéMON is marvelous.\p"
    .string "{PLAYER}!\n"
    .string "Come with me!$"

