SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
    .string "This ship, she is a luxury liner for\n"
    .string "TRAINERS of the world!\p"
    .string "At every port, we hold parties with\n"
    .string "invited TRAINERS.$"

SSAnne_2F_Corridor_Text_RivalIntro::
    .string "{RIVAL}: Bonjour!\n"
    .string "{PLAYER}!\p"
    .string "Imagine seeing you here!\n"
    .string "{PLAYER}, were you really invited?\p"
    .string "So how's your POKéDEX coming?\p"
    .string "I already caught 40 kinds, pal.\n"
    .string "Different kinds are everywhere.\p"
    .string "Crawl around in grassy areas, and\n"
    .string "look hard for them.\p"
    .string "My POKéMON…\n"
    .string "…were weak!\p"
    .string "They didn't make it.\n"
    .string "So I discarded them.\p"
    .string "But it's ok because these new\n"
    .string "ones are so much tougher!\p"
    .string "Come on! I'll show you!$"

SSAnne_2F_Corridor_Text_RivalDefeat::
    .string "Humph!\p"
    .string "At least you're raising your\n"
    .string "POKéMON!$"

SSAnne_2F_Corridor_Text_RivalVictory::
    .string "{PLAYER}‥！\n"
    .string "ふなよい　してるのか！\p"
    .string "もっと　からだ\n"
    .string "きたえた　ほうが　いいぜ！$"

SSAnne_2F_Corridor_Text_RivalPostBattle::
    .string "{RIVAL}: I heard there was a CUT\n"
    .string "master on board.\p"
    .string "But he was just a seasick old man!\p"
    .string "CUT itself is really useful.\n"
    .string "Yup, it'll be handy.\p"
    .string "You should go see him, too.\n"
    .string "Smell ya!$"

