CeladonCity_Restaurant_Text_TakingBreakRightNow::
    .string "Hi!\p"
    .string "Sorry, but we're taking a break\n"
    .string "right now.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
    .string "My POKéMON are weak, so I often\n"
    .string "have to go to the DRUGSTORE.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
    .string "Psst! There's a basement under the\n"
    .string "GAME CORNER, I hear.$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
    .string "Munch…\p"
    .string "The man at that table won it all\n"
    .string "at the slots.$"

CeladonCity_Restaurant_Text_TakeThisImBusted::
    .string "Go ahead! Laugh!\n"
    .string "I'm flat-out busted!\p"
    .string "No more slots for me!\n"
    .string "I'm going straight!\p"
    .string "Here!\n"
    .string "I won't be needing this anymore!$"

CeladonCity_Restaurant_Text_TakeTheseCoins::
    .string "I just won the jackpot!\n"
    .string "I'm rolling in it!\p"
    .string "No more slots for me!\n"
    .string "I'm going straight!\p"
    .string "Here!\n"
    .string "I bought everything I wanted!\p"
    .string "I won't be needing these anymore!$"

CeladonCity_Restaurant_Text_ReceivedCoinsFromMan::
    .string "{PLAYER} received 9,999 coins\n"
    .string "from the man!$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
    .string "{PLAYER} received a COIN CASE\n"
    .string "from the man.$"

CeladonCity_Restaurant_Text_MakeRoomForThis::
    .string "Make room for this!$"

CeladonCity_Restaurant_Text_GetACoinCaseFirst::
    .string "Come back when you have a\n"
    .string "COIN CASE. I'll give you\p"
    .string "something nice!$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
    .string "I always thought I was going to\n"
    .string "win it back…$"

CeladonCity_Restaurant_Text_EnjoyYourCoins::
    .string "I hope you enjoy your coins!$"
