PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MOM: …Right.\n"
    .string "All boys leave home someday.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MOM: …Right.\n"
    .string "All girls dream of traveling.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "Here, have a quick rest.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MOM: Oh, good! You and your\n"
    .string "POKéMON are looking great.\l"
    .string "Take care now!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "There's a movie on TV.\n"
    .string "Four boys are walking on railroad\l"
    .string "tracks.\p"
    .string "…I better go, too.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "There's a movie on TV.\n"
    .string "A girl with her hair in pigtails is\l"
    .string "walking up a brick road.\p"
    .string "…I better go, too.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Oops, wrong side…$"

PalletTown_PlayersHouse_1F_Text_MomAskHeal::
    .string "MOM: {PLAYER}!\n"
    .string "Would you like to rest?$"

PalletTown_PlayersHouse_1F_Text_MomAskPracticeBattle::
    .string "What about having a practice battle?$"

PalletTown_PlayersHouse_1F_Text_MomAskChangeGameMode::
    .string "Want to change game mode?$"

PalletTown_PlayersHouse_1F_Text_MomTakeCare::
    .string "Take care of yourself, Honey.$"

PalletTown_PlayersHouse_Text_MomPracticeBattleIntro::
    .string "Ok, but go easy on your momma, okay?$"

PalletTown_PlayersHouse_Text_MomPracticeBattleDefeat::
    .string "Very impressive, hun.$"

PalletTown_PlayersHouse_Text_MomPracticeBattlePostBattle::
    .string "You're so good at battling!\n"
    .string "You're doing great, hun.$"

PalletTown_PlayersHouse_1F_Text_WhichGameMode::
    .string "Which game mode would you\n"
    .string "like to switch to?$"

PalletTown_PlayersHouse_1F_Text_GameModeIsStandard::
    .string "Your game mode is set to STANDARD.$"

PalletTown_PlayersHouse_1F_Text_GameModeIsNowStandard::
    .string "Your game mode is now set to\n"
    .string "STANDARD.$"

PalletTown_PlayersHouse_1F_Text_GameModeAlreadyStandard::
    .string "Your game mode was already\n"
    .string "STANDARD.$"

PalletTown_PlayersHouse_1F_Text_GameModeIsLimited::
    .string "Your game mode is set to LIMITED.$"

PalletTown_PlayersHouse_1F_Text_GameModeIsNowLimited::
    .string "Your game mode is now set to\n"
    .string "LIMITED.$"

PalletTown_PlayersHouse_1F_Text_GameModeAlreadyLimited::
    .string "Your game mode was already\n"
    .string "LIMITED.$"

PalletTown_PlayersHouse_1F_Text_GameModeIsNuzlocke::
    .string "Your game mode is set to NUZLOCKE.$"

PalletTown_PlayersHouse_1F_Text_GameModeIsNowNuzlocke::
    .string "Your game mode is now set to\n"
    .string "NUZLOCKE.$"

PalletTown_PlayersHouse_1F_Text_GameModeAlreadyNuzlocke::
    .string "Your game mode was already\n"
    .string "NUZLOCKE.$"

PalletTown_PlayersHouse_1F_Text_GameModeIsInvalid::
    .string "Your game mode is invalid!\n"
    .string "Please change it ASAP!$"
