CeruleanCity_Text_RivalIntro::
    .string "{RIVAL}: Yo! {PLAYER}!\p"
    .string "You're still struggling along back\n"
    .string "here?\p"
    .string "My POKéMON…\n"
    .string "…were weak!\p"
    .string "They didn't make it.\n"
    .string "So I discarded them.\p"
    .string "But it's ok because these new\n"
    .string "ones are so much tougher!\p"
    .string "Come on! I'll show you!$"

CeruleanCity_Text_RivalDefeat::
    .string "Hey!\n"
    .string "Take it easy!\l"
    .string "You won already!$"

CeruleanCity_Text_RivalPostBattle::
    .string "{RIVAL}: Hey, guess what?\p"
    .string "I went to BILL's and got him to\n"
    .string "show me his rare POKéMON.\p"
    .string "That added a lot of pages to my\n"
    .string "POKéDEX!\p"
    .string "After all, BILL's world famous as a\n"
    .string "POKéMANIAC.\p"
    .string "He invented the POKéMON Storage\n"
    .string "System on PC, too.\p"
    .string "Since you're using his system,\n"
    .string "you should go thank him.\p"
    .string "Well, I better get rolling!\n"
    .string "Smell ya later!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .string "Oh, yeah, right.\p"
    .string "I feel sorry for you. No, really.\n"
    .string "You're always plodding behind me.\p"
    .string "So here, I'll give you a little\n"
    .string "present as a favor.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .string "You know, since you're always…\n"
    .string "lagging behind me? Get it?\p"
    .string "That thing's perfect.\p"
    .string "All right, this time I really am\n"
    .string "gone. Smell ya!$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory::
    .string "なんたって！\n"
    .string "おれは　てんさい　だからよ！$"

CeruleanCity_Text_GruntIntro::
    .string "Hey! Stay out!\n"
    .string "It's not your yard!\p"
    .string "…Huh?\n"
    .string "Me?\p"
    .string "I'm an innocent bystander!\n"
    .string "Don't you believe me?{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

CeruleanCity_Text_GruntDefeat::
    .string "GRUNT: Stop! I give up!\n"
    .string "I'll leave quietly!$"

CeruleanCity_Text_OkayIllReturnStolenTM::
    .string "…Okay.\n"
    .string "I'll return the TMs I stole.$"

CeruleanCity_Text_RecoveredTM_ZAP_CANNON_FromGrunt::
    .string "{PLAYER} recovered TM71 from\n"
    .string "the TEAM ROCKET GRUNT.$"

CeruleanCity_Text_RecoveredTM_INFERNO_FromGrunt::
    .string "{PLAYER} recovered TM72 from\n"
    .string "the TEAM ROCKET GRUNT.$"

CeruleanCity_Text_BetterGetMovingBye::
    .string "I better get moving!\n"
    .string "Bye!$"

CeruleanCity_Text_MakeRoomForThisCantRun::
    .string "Make room for this!\n"
    .string "I can't run until I give it to you!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
    .string "You're a TRAINER, too?\p"
    .string "Collecting, battling…\n"
    .string "It's a tough life, isn't it?$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
    .string "Did you know that you can CUT down\n"
    .string "small trees?\p"
    .string "Even that small tree in front of\n"
    .string "the shop can be CUT down.\p"
    .string "I think there's a way around it,\n"
    .string "though.$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
    .string "If that SLOWBRO wasn't there, you\n"
    .string "could CUT down the small tree.\p"
    .string "That way, you could get to the\n"
    .string "other side.\p"
    .string "I think there's a way around it,\n"
    .string "though.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .string "You're making an encyclopedia on\n"
    .string "POKéMON? That sounds amusing.$"

CeruleanCity_Text_PeopleHereWereRobbed::
    .string "The people here say they were\n"
    .string "robbed. But it's obvious that\l"
    .string "they just made it up!\p"
    .string "Our POLICE FORCE searched their\n"
    .string "home, and couldn't find anything\p"
    .string "of value. So they're obviously\n"
    .string "just poor and making things up.$"

CeruleanCity_Text_SlowbroUseSonicboom::
    .string "Okay! SLOWBRO!\n"
    .string "Use SONICBOOM!$"

CeruleanCity_Text_SlowbroPayAttention::
    .string "Come on, SLOWBRO, pay attention!$"

CeruleanCity_Text_SlowbroPunch::
    .string "SLOWBRO, punch!$"

CeruleanCity_Text_NoYouBlewItAgain::
    .string "No!\n"
    .string "You blew it again!$"

CeruleanCity_Text_SlowbroWithdraw::
    .string "SLOWBRO, WITHDRAW!$"

CeruleanCity_Text_HardToControlMonsObedience::
    .string "No! That's wrong!\n"
    .string "It's so hard to control POKéMON!\p"
    .string "Your POKéMON's obedience depends\n"
    .string "on your abilities as a TRAINER.$"

CeruleanCity_Text_SlowbroTookSnooze::
    .string "SLOWBRO took a snooze…$"

CeruleanCity_Text_SlowbroLoafingAround::
    .string "SLOWBRO is loafing around…$"

CeruleanCity_Text_SlowbroTurnedAway::
    .string "SLOWBRO turned away…$"

CeruleanCity_Text_SlowbroIgnoredOrders::
    .string "SLOWBRO ignored orders…$"

CeruleanCity_Text_WantBrightRedBicycle::
    .string "I want a bright red bicycle.\p"
    .string "I'll keep it at home, so it won't\n"
    .string "get dirty.$"

CeruleanCity_Text_ThisIsCeruleanCave::
    .string "This is CERULEAN CAVE.\p"
    .string "Horribly strong POKéMON live inside\n"
    .string "there.\p"
    .string "It takes a very special TRAINER to\n"
    .string "be allowed inside there.\p"
    .string "You'd have to be strong enough to\n"
    .string "become the POKéMON LEAGUE\l"
    .string "CHAMPION for starters.\p"
    .string "And, you would have to have\n"
    .string "made a great achievement.$"

CeruleanCity_Text_CitySign::
    .string "CERULEAN CITY\n"
    .string "A Mysterious, Blue Aura Surrounds\l"
    .string "It$"

CeruleanCity_Text_TrainerTipsHeldItems::
    .string "TRAINER TIPS\p"
    .string "A POKéMON can be made to hold\n"
    .string "an item.\p"
    .string "Some items can even be used by\n"
    .string "the holding POKéMON in battle.$"

CeruleanCity_Text_BikeShopSign::
    .string "Grass and caves handled easily!\n"
    .string "BIKE SHOP$"

CeruleanCity_Text_GymSign::
    .string "CERULEAN CITY POKéMON GYM\n"
    .string "LEADER: MISTY\l"
    .string "The Tomboyish Mermaid!$"

CeruleanCity_Text_ChloeIntro::
    .string "Sometimes I come out here in our\n"
    .string "backyard and think about MISTY,\l"
    .string "the CERULEAN CITY GYM LEADER.\p"
    .string "She's so pretty and strong and\n"
    .string "amazing and so so pretty!\p"
    .string "MISTY will occasionally practice\n"
    .string "with her pokemon in this little\p"
    .string "body of water behind our house and\n"
    .string "I'll come out here and watch her.\p"
    .string "One day when I grow up I want to\n"
    .string "be just like her! That's my dream.\p"
    .string "Anyway, do you want to battle?$"

CeruleanCity_Text_ChloeDefeat::
    .string "Oh, wow!$"

CeruleanCity_Text_ChloePostBattle::
    .string "You're strong too, just like MISTY!$"

