VermilionCity_House2_Text_ThatsTooBad::
	.string "That's too bad.$"

VermilionCity_House2_Text_ThisIsNoMon::
	.string "…This is no {STR_VAR_1}.\p"
	.string "If you get one, please trade it\n"
	.string "to me!$"

VermilionCity_House2_Text_ThankYou::
	.string "Thank you!$"

VermilionCity_House2_Text_DanielleIntro::
	.string "How is my old {STR_VAR_2}?\p"
	.string "The one you traded me is doing\n"
	.string "great, and I'm raising it well!\p"
	.string "Would you like to see some of\n"
	.string "my other POKéMON? I'll show\l"
	.string "you my Lv50 competition team!$"

VermilionCity_House2_Text_DanielleDefeat::
	.string "Oh, you're strong!$"

VermilionCity_House2_Text_DaniellePostBattle::
	.string "I'll raise my {STR_VAR_1}\n"
	.string "to be even stronger than them!$"

VermilionCity_House2_Text_HowIsMyOldMon::
	.string "How is my old {STR_VAR_2}?\p"
	.string "The one you traded me is doing\n"
	.string "great, and I'm raising it well!$"

