CeladonCity_Text_GotMyKoffingInCinnabar::
    .string "I got my KOFFING in CINNABAR.\p"
    .string "It's usually nice, but it breathes\n"
    .string "poison when it's angry.$"

CeladonCity_Text_GymIsGreatFullOfWomen::
    .string "Heheh! This GYM is great!\n"
    .string "It's full of women!$"

CeladonCity_Text_GameCornerIsBadForCitysImage::
    .string "CELADON takes pride in its efforts\n"
    .string "to keep the city beautiful.\p"
    .string "That's why the new GAME CORNER is\n"
    .string "bad for our city's image.$"

CeladonCity_Text_BlewItAllAtSlots::
    .string "Moan…\n"
    .string "I blew it all at the slots!\p"
    .string "I knew I should have cashed in my\n"
    .string "COINS for prizes!$"

CeladonCity_Text_MyTrustedPalPoliwrath::
    .string "This is my trusted pal, POLIWRATH.\p"
    .string "It evolved from a POLIWHIRL when\n"
    .string "I used a WATER STONE.$"

CeladonCity_Text_Poliwrath::
    .string "POLIWRATH: Ribi ribit!$"

CeladonCity_Text_GetLostOrIllPunchYou::
    .string "What are you staring at?\n"
    .string "Get lost, or I'll punch you.$"

CeladonCity_Text_KeepOutOfTeamRocketsWay::
    .string "Keep out of TEAM ROCKET's way!$"

CeladonCity_Text_ExplainXAccuracyDireHit::
    .string "TRAINER TIPS\p"
    .string "X ACCURACY boosts the accuracy of\n"
    .string "techniques.\p"
    .string "DIRE HIT jacks up the likelihood\n"
    .string "of critical hits.\p"
    .string "Get your items at the CELADON\n"
    .string "DEPT. STORE!$"

CeladonCity_Text_CitySign::
    .string "CELADON CITY\n"
    .string "The City of Rainbow Dreams$"

CeladonCity_Text_GymSign::
    .string "CELADON CITY POKéMON GYM\n"
    .string "LEADER: ERIKA\l"
    .string "The Nature-Loving Princess!$"

CeladonCity_Text_MansionSign::
    .string "CELADON MANSION$"

CeladonCity_Text_DeptStoreSign::
    .string "Find what you need at the\n"
    .string "CELADON DEPT. STORE!$"

CeladonCity_Text_GuardSpecProtectsFromStatus::
    .string "TRAINER TIPS\p"
    .string "GUARD SPEC. protects POKéMON\n"
    .string "from status-reduction moves during\l"
    .string "battle.\p"
    .string "Get your items at the\n"
    .string "CELADON DEPT. STORE!$"

CeladonCity_Text_PrizeExchangeSign::
    .string "COINS exchanged for prizes!\n"
    .string "PRIZE EXCHANGE$"

CeladonCity_Text_GameCornerSign::
    .string "ROCKET GAME CORNER\n"
    .string "The playground for grown-ups!$"

CeladonCity_Text_ScaldedTongueOnTea::
    .string "Aaaagh, ow…\n"
    .string "I scalded my tongue!\p"
    .string "This nice old lady in the MANSION\n"
    .string "gave me some TEA.\p"
    .string "But it was boiling hot!\n"
    .string "Gotta cool it to drink it.$"

Text_SoftboiledTeach::
    .string "Hello, there!\p"
    .string "I've seen you about, but I never\n"
    .string "had a chance to chat.\p"
    .string "It must be good luck that brought\n"
    .string "us together finally.\p"
    .string "I'd like to celebrate by teaching\n"
    .string "you the move CELEBRATE.$"

Text_SoftboiledDeclined::
    .string "I'll always be keeping an eye out\n"
    .string "for you.\p"
    .string "I hope we can chat again.$"

Text_SoftboiledWhichMon::
    .string "So, who's the POKéMON that gets\n"
    .string "the chance to learn CELEBRATE?$"

Text_SoftboiledTaught::
    .string "I wish you the best of luck!$"

CeladonCity_Text_SomeoneStoleSilphScope::
    .string "Oh, what am I to do…\p"
    .string "Someone stole our SILPH SCOPE.\p"
    .string "The thief came running this way,\n"
    .string "I'm sure of it.\p"
    .string "But I lost sight of him!\n"
    .string "Where'd he go?$"

CeladonCity_Text_EmilyIntro::
    .string "Hi! I'm EMILY!\p"
    .string "Recently in a dream, someone came\n"
    .string "to visit me from the future.\p"
    .string "She said her name was KAREN, and\n"
    .string "she gave me some important advice:\p"
    .string "''Strong POKéMON. Weak POKéMON.\n"
    .string "That is only the selfish perception\l"
    .string "of people.\p"
    .string "Truly skilled trainers should try\n"
    .string "to win with their favorites.''\p"
    .string "That really moved me, and I then\n"
    .string "and there decided to stop using the\p"
    .string "so-called ''best'' POKéMON just for\n"
    .string "their crazy BSTs or raw power.\p"
    .string "You won't catch me sporting mega-ray\n"
    .string "like DANI, for instance, no offense.\p"
    .string "I really like using weird gimmicky\n"
    .string "hackmons, and trying to make the\p"
    .string "most of my less popular favorites,\n"
    .string "such as Lanturn or Jumpluff.\p"
    .string "Wanna see what I can do?\p"
    .string "I won't be your toughest fight by\n"
    .string "any stretch of the imagination,\l"
    .string "but I promise you I'll have fun!\p"
    .string "Let's go!$"

CeladonCity_Text_EmilyRematchIntro::
    .string "Let's go!$"

CeladonCity_Text_EmilyDefeat::
    .string "Great work!$"

CeladonCity_Text_EmilyPostBattle::
    .string "So, did you use your favorites to\n"
    .string "beat me? If so, give yourself a\l"
    .string "well-deserved pat on the back.\p"
    .string "If not, that's ok, but I would\n"
    .string "encourage you to reconsider what\p"
    .string "motivates you to engage in POKéMON\n"
    .string "battles.\p"
    .string "In any case, please have yourself a\n"
    .string "lovely day today! And talk to me\l"
    .string "again if you ever desire a rematch!$"

CeladonCity_Text_EmilyPreTR100::
    .string "{PLAYER}, hold on one sec!$"

CeladonCity_Text_EmilyGotTR100::
    .string "{PLAYER} received TR100\n"
    .string "from EMILY.$"

CeladonCity_Text_EmilyPostTR100::
    .string "TR100 contains PHOENIX CALL.\n"
    .string "Use it to resurrect the fallen.$"

CeladonCity_Text_EmilyNextIsJuliana::
    .string "Now you can fight JULIANA at the\n"
    .string "INDIGO PLATEAU. Good luck!$"

