ViridianCity_House_Text_NicknamingIsFun::
    .string "Coming up with nicknames is fun,\n"
    .string "but it's not so easy to do.\p"
    .string "Clever names are nice, but simple\n"
    .string "names are easier to remember.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "My daddy loves POKéMON, too.$"

ViridianCity_House_Text_AnnaIntro::
    .string "My daddy loves POKéMON, too.\p"
    .string "I'll show you what he taught me.$"

ViridianCity_House_Text_AnnaDefeat::
    .string "NOOOOOOOOO!$"

ViridianCity_House_Text_YouKilledMrCuddles::
    .string "You killed Mr Cuddles!$"

ViridianCity_House_Text_Speary::
    .string "SPEARY: Tetweet!$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "SPEAROW\n"
    .string "Name: SPEARY$"

